Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job stats:
job                 count
----------------  -------
tex2pdf_with_bib        1
total                   1

Resources before job selection: {'_cores': 24, '_nodes': 9223372036854775807}
Ready jobs (1)
Select jobs to execute...
Using greedy selector because only single job has to be scheduled.
Selected jobs (1)
Resources after job selection: {'_cores': 23, '_nodes': 9223372036854775806}

[Thu Oct 24 04:35:55 2024]
rule tex2pdf_with_bib:
    input: workflow/hcg_paper.tex
    output: outputs/publication/hcg_paper.pdf
    jobid: 0
    reason: Missing output files: outputs/publication/hcg_paper.pdf
    resources: mem_mb=1000, mem_mib=954, disk_mb=1000, disk_mib=954, tmpdir=/data

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/Snakefile", line 78, in __rule_tex2pdf_with_bib
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  

        tectonic -o outputs/publication workflow/hcg_paper.tex
        for file in *delete*; do
            if [ -f "$file" ]; then
                rm -f "$file"
            fi
        done' returned non-zero exit status 1.

[Thu Oct 24 04:35:57 2024]
Error in rule tex2pdf_with_bib:
    jobid: 0
    input: workflow/hcg_paper.tex
    output: outputs/publication/hcg_paper.pdf
    shell:
        

        tectonic -o outputs/publication workflow/hcg_paper.tex
        for file in *delete*; do
            if [ -f "$file" ]; then
                rm -f "$file"
            fi
        done        
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/Snakefile", line 78, in __rule_tex2pdf_with_bib
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  

        tectonic -o outputs/publication workflow/hcg_paper.tex
        for file in *delete*; do
            if [ -f "$file" ]; then
                rm -f "$file"
            fi
        done' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /data/workflow/Snakefile, line 49:
Command 'set -euo pipefail;  

        tectonic -o outputs/publication workflow/hcg_paper.tex
        for file in *delete*; do
            if [ -f "$file" ]; then
                rm -f "$file"
            fi
        done' returned non-zero exit status 1.
  File "/data/workflow/Snakefile", line 49, in __rule_tex2pdf_with_bib

RuleException:
CalledProcessError in file /data/workflow/Snakefile, line 49:
Command 'set -euo pipefail;  

        tectonic -o outputs/publication workflow/hcg_paper.tex
        for file in *delete*; do
            if [ -f "$file" ]; then
                rm -f "$file"
            fi
        done' returned non-zero exit status 1.
  File "/data/workflow/Snakefile", line 49, in __rule_tex2pdf_with_bib
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-24T043554.977194.snakemake.log
unlocking
removing lock
removing lock
removed all locks
