Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job stats:
job                         count
------------------------  -------
plot_gbt_meerkat_spectra        6
plot_gbt_vs_meerkat_flux        1
tex2pdf_with_bib                1
total                           8

Resources before job selection: {'_cores': 24, '_nodes': 9223372036854775807}
Ready jobs (6)
Select jobs to execute...
Selected jobs (6)
Resources after job selection: {'_cores': 18, '_nodes': 9223372036854775801}

[Tue Oct 22 10:12:27 2024]
rule plot_gbt_meerkat_spectra:
    input: results/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits, outputs/publication/figures/ngc1622_column_density.pdf, outputs/publication/figures/ngc1622_snr.pdf, outputs/publication/figures/ngc1622_mom1.pdf, outputs/publication/figures/ngc1622_chan.pdf, outputs/publication/figures/ngc1622_mom2.pdf, outputs/publication/figures/ngc1622_spec.pdf
    output: outputs/publication/figures/hcg16_meerkat_gbt_spec.pdf
    jobid: 8
    reason: Missing output files: outputs/publication/figures/hcg16_meerkat_gbt_spec.pdf
    wildcards: gal_idx=hcg16
    priority: 98
    resources: mem_mb=1079, mem_mib=1030, disk_mb=1079, disk_mib=1030, tmpdir=/tmp


[Tue Oct 22 10:12:27 2024]
rule plot_gbt_meerkat_spectra:
    input: results/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits, outputs/publication/figures/ngc1622_column_density.pdf, outputs/publication/figures/ngc1622_snr.pdf, outputs/publication/figures/ngc1622_mom1.pdf, outputs/publication/figures/ngc1622_chan.pdf, outputs/publication/figures/ngc1622_mom2.pdf, outputs/publication/figures/ngc1622_spec.pdf
    output: outputs/publication/figures/hcg31_meerkat_gbt_spec.pdf
    jobid: 10
    reason: Missing output files: outputs/publication/figures/hcg31_meerkat_gbt_spec.pdf
    wildcards: gal_idx=hcg31
    priority: 98
    resources: mem_mb=1901, mem_mib=1813, disk_mb=1901, disk_mib=1813, tmpdir=/tmp


[Tue Oct 22 10:12:27 2024]
rule plot_gbt_meerkat_spectra:
    input: results/data/hcg91/hcg91_line60_masked.pb_corr_vopt.fits, outputs/publication/figures/ngc1622_column_density.pdf, outputs/publication/figures/ngc1622_snr.pdf, outputs/publication/figures/ngc1622_mom1.pdf, outputs/publication/figures/ngc1622_chan.pdf, outputs/publication/figures/ngc1622_mom2.pdf, outputs/publication/figures/ngc1622_spec.pdf
    output: outputs/publication/figures/hcg91_meerkat_gbt_spec.pdf
    jobid: 12
    reason: Missing output files: outputs/publication/figures/hcg91_meerkat_gbt_spec.pdf
    wildcards: gal_idx=hcg91
    priority: 98
    resources: mem_mb=3324, mem_mib=3171, disk_mb=3324, disk_mib=3171, tmpdir=/tmp


[Tue Oct 22 10:12:27 2024]
rule plot_gbt_meerkat_spectra:
    input: results/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits, outputs/publication/figures/ngc1622_column_density.pdf, outputs/publication/figures/ngc1622_snr.pdf, outputs/publication/figures/ngc1622_mom1.pdf, outputs/publication/figures/ngc1622_chan.pdf, outputs/publication/figures/ngc1622_mom2.pdf, outputs/publication/figures/ngc1622_spec.pdf
    output: outputs/publication/figures/hcg30_meerkat_gbt_spec.pdf
    jobid: 9
    reason: Missing output files: outputs/publication/figures/hcg30_meerkat_gbt_spec.pdf
    wildcards: gal_idx=hcg30
    priority: 98
    resources: mem_mb=1214, mem_mib=1158, disk_mb=1214, disk_mib=1158, tmpdir=/tmp


[Tue Oct 22 10:12:27 2024]
rule plot_gbt_meerkat_spectra:
    input: results/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits, outputs/publication/figures/ngc1622_column_density.pdf, outputs/publication/figures/ngc1622_snr.pdf, outputs/publication/figures/ngc1622_mom1.pdf, outputs/publication/figures/ngc1622_chan.pdf, outputs/publication/figures/ngc1622_mom2.pdf, outputs/publication/figures/ngc1622_spec.pdf
    output: outputs/publication/figures/hcg90_meerkat_gbt_spec.pdf
    jobid: 11
    reason: Missing output files: outputs/publication/figures/hcg90_meerkat_gbt_spec.pdf
    wildcards: gal_idx=hcg90
    priority: 98
    resources: mem_mb=2217, mem_mib=2115, disk_mb=2217, disk_mib=2115, tmpdir=/tmp


[Tue Oct 22 10:12:27 2024]
rule plot_gbt_meerkat_spectra:
    input: results/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits, outputs/publication/figures/ngc1622_column_density.pdf, outputs/publication/figures/ngc1622_snr.pdf, outputs/publication/figures/ngc1622_mom1.pdf, outputs/publication/figures/ngc1622_chan.pdf, outputs/publication/figures/ngc1622_mom2.pdf, outputs/publication/figures/ngc1622_spec.pdf
    output: outputs/publication/figures/hcg97_meerkat_gbt_spec.pdf
    jobid: 13
    reason: Missing output files: outputs/publication/figures/hcg97_meerkat_gbt_spec.pdf
    wildcards: gal_idx=hcg97
    priority: 98
    resources: mem_mb=1450, mem_mib=1383, disk_mb=1450, disk_mib=1383, tmpdir=/tmp

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 40, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.

[Tue Oct 22 10:12:44 2024]
Error in rule plot_gbt_meerkat_spectra:
    jobid: 11
    input: results/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits, outputs/publication/figures/ngc1622_column_density.pdf, outputs/publication/figures/ngc1622_snr.pdf, outputs/publication/figures/ngc1622_mom1.pdf, outputs/publication/figures/ngc1622_chan.pdf, outputs/publication/figures/ngc1622_mom2.pdf, outputs/publication/figures/ngc1622_spec.pdf
    output: outputs/publication/figures/hcg90_meerkat_gbt_spec.pdf
    shell:
        python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 40, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 26:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 26, in __rule_plot_gbt_meerkat_spectra

RuleException:
CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 26:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 26, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 40, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.

[Tue Oct 22 10:12:44 2024]
Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 40, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.

Error in rule plot_gbt_meerkat_spectra:
    jobid: 13
    input: results/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits, outputs/publication/figures/ngc1622_column_density.pdf, outputs/publication/figures/ngc1622_snr.pdf, outputs/publication/figures/ngc1622_mom1.pdf, outputs/publication/figures/ngc1622_chan.pdf, outputs/publication/figures/ngc1622_mom2.pdf, outputs/publication/figures/ngc1622_spec.pdf
    output: outputs/publication/figures/hcg97_meerkat_gbt_spec.pdf
    shell:
        python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 40, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 26:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 26, in __rule_plot_gbt_meerkat_spectra

[Tue Oct 22 10:12:44 2024]
Error in rule plot_gbt_meerkat_spectra:
    jobid: 10
    input: results/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits, outputs/publication/figures/ngc1622_column_density.pdf, outputs/publication/figures/ngc1622_snr.pdf, outputs/publication/figures/ngc1622_mom1.pdf, outputs/publication/figures/ngc1622_chan.pdf, outputs/publication/figures/ngc1622_mom2.pdf, outputs/publication/figures/ngc1622_spec.pdf
    output: outputs/publication/figures/hcg31_meerkat_gbt_spec.pdf
    shell:
        python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 40, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 26:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 26, in __rule_plot_gbt_meerkat_spectra

RuleException:
CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 26:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 26, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
RuleException:
CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 26:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 26, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 40, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.

[Tue Oct 22 10:12:44 2024]
Error in rule plot_gbt_meerkat_spectra:
    jobid: 9
    input: results/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits, outputs/publication/figures/ngc1622_column_density.pdf, outputs/publication/figures/ngc1622_snr.pdf, outputs/publication/figures/ngc1622_mom1.pdf, outputs/publication/figures/ngc1622_chan.pdf, outputs/publication/figures/ngc1622_mom2.pdf, outputs/publication/figures/ngc1622_spec.pdf
    output: outputs/publication/figures/hcg30_meerkat_gbt_spec.pdf
    shell:
        python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 40, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 26:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 26, in __rule_plot_gbt_meerkat_spectra

RuleException:
CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 26:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 135.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 26, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 40, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

[Tue Oct 22 10:12:45 2024]
Error in rule plot_gbt_meerkat_spectra:
    jobid: 8
    input: results/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits, outputs/publication/figures/ngc1622_column_density.pdf, outputs/publication/figures/ngc1622_snr.pdf, outputs/publication/figures/ngc1622_mom1.pdf, outputs/publication/figures/ngc1622_chan.pdf, outputs/publication/figures/ngc1622_mom2.pdf, outputs/publication/figures/ngc1622_spec.pdf
    output: outputs/publication/figures/hcg16_meerkat_gbt_spec.pdf
    shell:
        python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 40, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 26:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 26, in __rule_plot_gbt_meerkat_spectra

RuleException:
CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 26:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 26, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 40, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg91/hcg91_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

[Tue Oct 22 10:12:47 2024]
Error in rule plot_gbt_meerkat_spectra:
    jobid: 12
    input: results/data/hcg91/hcg91_line60_masked.pb_corr_vopt.fits, outputs/publication/figures/ngc1622_column_density.pdf, outputs/publication/figures/ngc1622_snr.pdf, outputs/publication/figures/ngc1622_mom1.pdf, outputs/publication/figures/ngc1622_chan.pdf, outputs/publication/figures/ngc1622_mom2.pdf, outputs/publication/figures/ngc1622_spec.pdf
    output: outputs/publication/figures/hcg91_meerkat_gbt_spec.pdf
    shell:
        python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg91/hcg91_line60_masked.pb_corr_vopt.fits
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 40, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg91/hcg91_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 26:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg91/hcg91_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 26, in __rule_plot_gbt_meerkat_spectra

RuleException:
CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 26:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube results/data/hcg91/hcg91_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 26, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-22T101226.134064.snakemake.log
unlocking
removing lock
removing lock
removed all locks
